/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfigForm: typeof import('./components/ConfigForm.vue')['default']
    DirCard: typeof import('./components/DirCard.vue')['default']
    FfmpegStatusBar: typeof import('./components/FfmpegStatusBar.vue')['default']
    GlobalSettings: typeof import('./components/GlobalSettings.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NModal: typeof import('naive-ui')['NModal']
    NProgress: typeof import('naive-ui')['NProgress']
    NSpace: typeof import('naive-ui')['NSpace']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    TabConfig: typeof import('./components/tabs/TabConfig.vue')['default']
    TabHistory: typeof import('./components/tabs/TabHistory.vue')['default']
    TabPreview: typeof import('./components/tabs/TabPreview.vue')['default']
    TitleBar: typeof import('./components/TitleBar.vue')['default']
  }
}
